name: Simple Go Build Workflow

on:
  push:
    branches:
      -main
      
jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup go on runner
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      
      - run: go run aloha.go
